/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"


//==============================================================================
/**
*/
class TheGeneralAudioProcessorEditor  : public AudioProcessorEditor, private Slider::Listener
{
public:
    TheGeneralAudioProcessorEditor (TheGeneralAudioProcessor&);
    ~TheGeneralAudioProcessorEditor();

    //==============================================================================
    void paint (Graphics&) override;
    void resized() override;
    void sliderValueChanged (Slider* slider) override;

private:
    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    TheGeneralAudioProcessor& processor;
    
    Slider signalSlider;
    Slider generalFequencySlider;
    Slider volumeSlider;
    Slider onOffSlider;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (TheGeneralAudioProcessorEditor)
    
};


#endif  // PLUGINEDITOR_H_INCLUDED
